# SciFact
# dataset_name: "scifact"
# dataset_url: "https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/scifact.zip"

# NFCorpus 
dataset_name: "nfcorpus"
dataset_url: "https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/nfcorpus.zip"

# FiQA
# dataset_name: "fiqa"
# dataset_url: "https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip"

data_dir: "./data_eval"
embedding_model: "all-MiniLM-L6-v2"
reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
chunk_size: 200
overlap: 30